services:
  app:
    build:
      context: etc/
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./etc/frankenphp:/etc/caddy
      - ./etc/docker/hooks/bootstrap/40-fix-home:/etc/hooks/bootstrap/40-fix-home
    depends_on:
      - database
    networks:
      internal:
        ipv4_address: 192.168.19.10

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy
    container_name: imgproxy
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_AUTO_WEBP: true
      IMGPROXY_AUTO_AVIF: true
      IMGPROXY_AUTO_JXL: true
      IMGPROXY_LOG_LEVEL: info
    networks:
      - internal

  database:
    image: mariadb:lts
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      internal:
        ipv4_address: 192.168.19.11

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_WEBROOT: /mailpit
    networks:
      internal:
        ipv4_address: 192.168.19.12

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.19.0/24
